//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddit_News_Watcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reddit_News_Watcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;.+&quot; jsname=&quot;.+&quot; jsaction=&quot;click:.+;&quot; data-nav=&quot;\d+&quot; tabindex=&quot;\d+&quot; style=&quot;height: \d+px;&quot; href=&quot;(.+)&quot; data-deferred=&quot;\d+&quot;.
        /// </summary>
        internal static string GoogleImageRegex {
            get {
                return ResourceManager.GetString("GoogleImageRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;(.+)&quot; class=&quot;\S+ styled-outbound-link&quot; post=&quot;.+&quot; rel=&quot;noopener nofollow ugc&quot; target=&quot;_blank&quot;&gt;.+class=&quot;icon icon-outboundLink.+&lt;\/i&gt;&lt;\/a&gt;.
        /// </summary>
        internal static string SourceRegex {
            get {
                return ResourceManager.GetString("SourceRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 class=&quot;\S+&quot;&gt;(.+)&lt;\/h3&gt;&lt;\/div&gt;.
        /// </summary>
        internal static string TitleRegex {
            get {
                return ResourceManager.GetString("TitleRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button \S+&quot;upvote&quot; \S+ class=&quot;voteButton&quot; data-click-id=&quot;upvote&quot; id=&quot;upvote-button-\S+&quot;&gt;&lt;span class=&quot;.+&quot;&gt;&lt;i class=&quot;icon icon-upvote .+&quot;&gt;(.+)&lt;\/div&gt;&lt;button.
        /// </summary>
        internal static string VotesRegex {
            get {
                return ResourceManager.GetString("VotesRegex", resourceCulture);
            }
        }
    }
}
